@echo off
:: Generated by pybuildc

::----------Variables-----------::
set PROJECT="sandbox"
set CC="clang"
set BUILD_DIR=".build"
set CFLAGS=

::-------------Setup------------::
cd /D %~dp0

mkdir %BUILD_DIR%\bin 2>NUL
mkdir %BUILD_DIR%\obj 2>NUL

::---------Dependencies---------::
call ..\claymore\build.bat
cd /D %~dp0

::---------Compilation---------::
%CC% -I..\claymore\include -I..\claymore\src -I..\claymore\deps\stb_image\include -I..\claymore\deps\stb_image\src -I..\claymore\deps\stb_truetype\include -I..\claymore\deps\stb_truetype\src -I..\claymore\deps\miniaudio\include -I..\claymore\deps\miniaudio\src -I..\claymore\deps\glew\glew-win\include -I..\claymore\deps\glfw\glfw-win\include -I..\claymore\deps\cglm\cglm-win\cglm\include -Isrc -g -Wall -Wextra -Werror -Wpedantic -Wshadow -Wnull-dereference -Wformat=2 -D_CRT_SECURE_NO_WARNINGS -std=c11 -DCM_SCENES_MAX=10 %CFLAGS% src\camera.c src\fps.c src\gui\gui.c src\instancing\instancing.c src\light\light.c src\menu\menu_scene.c src\models\models.c src\noise\noise.c src\ortho\background.c src\ortho\ortho_layer.c src\ortho\ortho_scene.c src\particles\particle.c src\sandbox.c src\tests\tests.c src\texture\texture.c -o %BUILD_DIR%\bin\sandbox.exe -L.build\claymore\debug\bin -lclaymore -L..\claymore\.build\stb_image\release\bin -lstb_image -L..\claymore\.build\stb_truetype\release\bin -lstb_truetype -L..\claymore\.build\miniaudio\release\bin -lminiaudio -lShell32 -lUser32 -lGdi32 -lopengl32 -L..\claymore\deps\glew\glew-win\lib\Release\Win32 -lglew32s -L..\claymore\deps\glfw\glfw-win\lib-vc2022 -lglfw3_mt -L..\claymore\deps\cglm\cglm-win\build\Release -lcglm
