#!/bin/bash
# Generated by pybuildc

#----------Variables-----------#
PROJECT="sandbox"
CC="clang"
BUILD_DIR=".build"
CFLAGS=()

#-------------Setup------------#
SCRIPT_DIR=$(dirname "$0")
set -xe
cd $SCRIPT_DIR

BIN=$BUILD_DIR/bin/$PROJECT
mkdir -p $BUILD_DIR/bin
mkdir -p $BUILD_DIR/obj

#---------Dependencies---------#
bash ../claymore/build.sh

#---------Compilation---------#
$CC -I../claymore/include -I../claymore/src -I../claymore/deps/stb_image/include -I../claymore/deps/stb_image/src -I../claymore/deps/stb_truetype/include -I../claymore/deps/stb_truetype/src -I../claymore/deps/miniaudio/include -I../claymore/deps/miniaudio/src -I../claymore/deps/glew/glew-linux/glew/include -I../claymore/deps/glfw/glfw-linux/glfw/include -I../claymore/deps/cglm/cglm-linux/cglm/include -Isrc -g -Wall -Wextra -Werror -Wpedantic -Wshadow -Wnull-dereference -Wformat=2 -D_CRT_SECURE_NO_WARNINGS -std=c11 -DCM_SCENES_MAX=10 ${CFLAGS[@]} src/camera.c src/fps.c src/sandbox.c src/ortho/ortho_scene.c src/ortho/background.c src/ortho/ortho_layer.c src/light/light.c src/menu/menu_scene.c src/models/models.c src/gui/gui.c src/noise/noise.c src/tests/tests.c src/instancing/instancing.c src/particles/particle.c src/texture/texture.c -o $BIN -L.build/claymore/debug/bin -lclaymore -L../claymore/.build/stb_image/release/bin -lstb_image -L../claymore/.build/stb_truetype/release/bin -lstb_truetype -lm -L../claymore/.build/miniaudio/release/bin -lminiaudio -ldl -lpthread -lm -lGL -L../claymore/deps/glew/glew-linux/lib -lGLEW -L../claymore/deps/glfw/glfw-linux/build/src -lglfw3 -L../claymore/deps/cglm/cglm-linux/build -lcglm -lm
