[pybuildc]
name="sandbox"

cflags=["-fsanitize=address", "-Wno-static-in-inline"]

[exe]
sandbox="src/sandbox.c"
benchmark-2d="src/benchmark-2d.c"
basic="src/basic.c"
hello="src/hello.c"

[deps.claymore]
dir="../claymore/" 
type="pybuildc"
mode="debug"

