[pybuildc]
name="sandbox"
cc="clang"

cflags=["-fsanitize=address"]

[exe]
sandbox="src/sandbox.c"
texture_sandbox="src/texture_sandbox.c"

[deps.claymore]
dir="../claymore/" 
type="pybuildc"
target="debug"

