[pybuildc]
name="sandbox"

cflags=[
  # "-fsanitize=address",
]

[exe]
sandbox = "src/sandbox.c"
benchmark-2d = "src/benchmark-2d.c"
basic = "src/basic.c"
hello = "src/hello.c"
animation = "src/animation.c"
balls = "src/balls.c"
atlas = "src/atlas.c"

[libs.claymore]
dir = "../claymore/" 
type = "pybuildc"
mode = "debug"

