[pybuildc]
name="sandbox"

cflags=[
  # "-fsanitize=address",
  "-Wextra",
  "-Wall",
  "-Wpedantic",
  "-Werror",
  "-Wstrict-prototypes",
]

[exe]
sandbox = "src/sandbox.c"

[libs.claymore]
dir = "../claymore/" 
type = "pybuildc"
mode = "debug"

