[pybuildc]
name="sandbox"

cflags=[
  # "-fsanitize=address",
  "-Wextra",
  "-Wall",
  "-Wpedantic",
  "-Werror",
  "-Wstrict-prototypes",
]

[exe]
sandbox = "src/sandbox.c"
benchmark-2d = "src/benchmark-2d.c"
template = "src/template.c"
hello = "src/hello.c"

[libs.claymore]
dir = "../claymore/" 
type = "pybuildc"
mode = "debug"

