[pybuildc]
name="sandbox"
cc="clang"

cflags=["-fsanitize=address"]

[exe]
sandbox="src/sandbox.c"
texture="src/texture_sandbox.c"
benchmark-2d="src/benchmark-2d.c"

[deps.claymore]
dir="../claymore/" 
type="pybuildc"
target="debug"

