[pybuildc]
name = "RGFW"

[[scripts.build]]
cmd="sh"
args=["dependencies.sh"]

[deps.linux]
X11  = { l="X11" }
Xrandr  = { l="Xrandr" }
math = { l="m" }

[deps.windows]
Shell32 = { l="Shell32" }
User32  = { l="User32" }
Gdi32   = { l="Gdi32" }
