[project]
name="claymore"
version="0.1.0"
cc="gcc"
bin="static"

cflags=["-D_CM_DEBUG"]

[dependencies]
gl   = { lib="GL" }
glew = { lib="GLEW", dir="../deps/glew/glew/lib/", include=["../deps/glew/glew/include/"] }
glfw = { lib="glfw3", dir="../deps/glfw/glfw/build/src/", include=["../deps/glfw/glfw/include/"] }
math = { lib="m" }
cglm = { lib="cglm", dir="../deps/cglm/cglm/build/", include=["../deps/cglm/cglm/include/"]}
