[pybuildc]
name="claymore"
version="0.1.0"

cflags = ["-std=c99", "-DGLEW_STATIC", "-Wno-static-in-inline"]

[deps]
glad = { dir="deps/glad", type="pybuildc" }
stb_image = { dir="deps/stb_image/", type="pybuildc" }
stb_truetype = { dir="deps/stb_truetype/", type="pybuildc" }
miniaudio = { dir="deps/miniaudio/", type="pybuildc" }
cglm = { dir="deps/cglm/cglm", I=["include"] }

cebus = { dir = "../../cebus", type="pybuildc" }

[deps.linux]
glfw = { l="glfw3", dir="deps/glfw/glfw-linux", L="build/src", I=["glfw/include"] }
math = { l="m" }

[deps.windows]
Shell32 = { l="Shell32" }
User32  = { l="User32" }
Gdi32   = { l="Gdi32" }
glfw    = { l="glfw3_mt", dir="deps/glfw/glfw-win", L="lib-vc2022/", I=["include/"] }
