[pybuildc]
name="claymore"
version="0.1.0"

cflags = ["-std=c99"]

[deps]
RGFW         = { dir="dependencies/RGFW", type="pybuildc" }
glad         = { dir="dependencies/glad", type="pybuildc" }
stb_image    = { dir="dependencies/stb_image/", type="pybuildc" }
stb_truetype = { dir="dependencies/stb_truetype/", type="pybuildc" }
miniaudio    = { dir="dependencies/miniaudio/", type="pybuildc" }
cglm         = { dir="dependencies/cglm", I=["include"] }
cebus        = { dir="dependencies/cebus", type="pybuildc" }

