[project]
name="claymore"
version="0.1.0"
cc="clang"
bin="static"

cflags = ["-D_CRT_SECURE_NO_WARNINGS", "-std=c11"]

[dependencies]
stb_image = { dir="deps/stb_image/", dep_type="pybuildc" }
stb_truetype = { dir="deps/stb_truetype/", dep_type="pybuildc" }
miniaudio = { dir="deps/miniaudio/", dep_type="pybuildc" }

[dependencies.linux]
gl   = { lib="GL" }
glew = { lib="GLEW", dir="deps/glew/glew-linux/lib", include=["deps/glew/glew-linux/glew/include/"] }
glfw = { lib="glfw3", dir="deps/glfw/glfw-linux/build/src/", include=["deps/glfw/glfw-linux/glfw/include/"] }
cglm = { lib="cglm", dir="deps/cglm/cglm-linux/build", include=["deps/cglm/cglm-linux/cglm/include/"]}
math = { lib="m" }

[dependencies.windows]
Shell32 = { lib="Shell32" }
User32  = { lib="User32" }
Gdi32   = { lib="Gdi32" }
gl      = { lib="opengl32" }
glew    = { lib="glew32s", dir="deps/glew/glew-win/lib/Release/Win32", include=["deps/glew/glew-win/include/"] }
glfw    = { lib="glfw3_mt", dir="deps/glfw/glfw-win/lib-vc2022/", include=["deps/glfw/glfw-win/include/"] }
cglm    = { lib="cglm", dir="deps/cglm/cglm-win/build/Release", include=["deps/cglm/cglm-win/cglm/include"] }
