[project]
name="claymore"
version="0.1.0"
cc="clang"
bin="static"

cflags = ["-Wno-static-in-inline", "-D_CRT_SECURE_NO_WARNINGS"]

[dependencies]
stb_image = { dir="../deps/stb_image/", dep_type="pybuildc" }
stb_truetype = { dir="../deps/stb_truetype/", dep_type="pybuildc" }

[dependencies.linux]
gl   = { lib="GL" }
glew = { lib="GLEW", dir="../deps/glew/glew/lib/", include=["../deps/glew/glew/include/"] }
glfw = { lib="glfw3", dir="../deps/glfw/glfw/build/src/", include=["../deps/glfw/glfw/include/"] }
math = { lib="m" }
cglm = { lib="cglm", dir="../deps/cglm/cglm/build/", include=["../deps/cglm/cglm/include/"]}

[dependencies.windows]
Shell32 = { lib="Shell32" }
User32  = { lib="User32" }
Gdi32   = { lib="Gdi32" }
gl      = { lib="opengl32" }
glew    = { lib="glew32s", dir="../deps/glew/glew-win/lib/Release/Win32", include=["../deps/glew/glew-win/include/"] }
glfw    = { lib="glfw3_mt", dir="../deps/glfw/glfw-win/lib-vc2022/", include=["../deps/glfw/glfw-win/include/"] }
cglm    = { lib="cglm", dir="../deps/cglm/cglm-win/Release", include=["../deps/cglm/cglm/include"] }
