[pybuildc]
name="claymore"
version="0.1.0"

cflags = [
  "-std=c99", 
  "-fsanitize=address",
  "-Wextra",
  "-Wall",
  "-Wpedantic",
  "-Werror",
  "-Wstrict-prototypes",
]

[libs]
RGFW = { dir = "libs/RGFW", type = "pybuildc" }
glad = { dir = "libs/glad", type = "pybuildc" }
stb_image = { dir = "libs/stb_image/", type = "pybuildc" }
stb_truetype = { dir = "libs/stb_truetype/", type = "pybuildc" }
miniaudio = { dir = "libs/miniaudio/", type = "pybuildc" }
cglm = { dir = "libs/cglm", I = ["include"] }
cebus = { dir = "libs/cebus", type = "pybuildc" }

